name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: ARM runner
        uses: pguyot/arm-runner-action@v2.5.2
        id: build_image
        with:
          base_image: raspios_lite:2022-04-04
          commands: |
            echo "commands to build image"
      - name: Compress the release image
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
        run: |
          mv ${{ steps.build_image.outputs.image }} release-image.img
          xz -0 -T 0 -v release-image.img
        
            
