name: C/C++ CI

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    
jobs:
  build:
    permissions:
      contents: write
      packages: write 
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [armhf, arm64]
        include:
        - target: armhf
          cpu: cortex-a7
          base_image: raspios_lite:latest
        - target: arm64
          cpu: cortex-a53
          base_image: raspios_lite_arm64:latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: build 
      uses: pguyot/arm-runner-action@v2.5.2
      id: build_image
      with:
        image_additional_mb: 1024
        base_image: ${{ matrix.base_image }}
        cpu: ${{ matrix.cpu }}
        bind_mount_repository: true
        copy_artifact_path: gs-${{ matrix.target }}.zip
        commands: |
          echo "commands to build gs"
          cd ./gs
          mkdir ./dst
          apt-get update -y
          apt install -y libdrm-dev libgbm-dev libgles2-mesa-dev libpcap-dev libturbojpeg0-dev libts-dev libsdl2-dev libfreetype6-dev 
          make -j4
          ls ./ -faln
          mv gs ./dst/ 
          mv ../README.md ./dst/
          cd dst
          zip gs-${{ matrix.target }}.zip gs README.md
          cd ../../
          mv gs/dst/gs-${{ matrix.target }}.zip ./
